swappers/base/urls.py
from django.conf.urls import url
from base import views
from django.urls import include, path
from rest_framework import routers
# from .views import (
#     PostListView, 
#     PostDetailView, 
#     PostCreateView,
#     PostDeleteView,
#     TravelListView, 
#     TravelDetailView, 
#     TravelCreateView,
#     TravelDeleteView
# )

# urlpatterns = [
#     url('', views.home),
#     # url('', views.gallery)
# ]

app_name = 'base'

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('rest', include(router.urls)),
    path('home/', views.home, name='base-home'),
    path('travel/', views.TravelListView.as_view(), name='base-travel'),
    path('travel/new/', views.TravelCreateView.as_view(), name='travel-create'),
    path('travel/post/<int:pk>/delete', views.TravelDeleteView.as_view(), name='travel-delete'),
    path('travel/post/<int:pk>/update', views.TravelUpdateView.as_view(), name='travel-update'),
    path('travel/post/<int:pk>/', views.TravelDetailView.as_view(), name='travel-detail'),
    path('gallery', views.PostListView.as_view(), name='base-gallery'),
    path('gallery/post/<int:pk>/', views.PostDetailView.as_view(), name='post-detail'),
    path('gallery/new/', views.PostCreateView.as_view(), name='post-create'),
    path('gallery/post/<int:pk>/update', views.PostUpdateView.as_view(), name='post-update'),
    path('gallery/post/<int:pk>/delete', views.PostDeleteView.as_view(), name='post-delete'),
    path('food/', views.FoodListView.as_view(), name='base-food'),
    path('food/new/', views.FoodCreateView.as_view(), name='food-create'),
    path('food/post/<int:pk>/delete', views.FoodDeleteView.as_view(), name='food-delete'),
    path('food/post/<int:pk>/update', views.FoodUpdateView.as_view(), name='food-update'),
    path('food/post/<int:pk>/', views.FoodDetailView.as_view(), name='food-detail'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

swappers/swappers/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('register/', user_views.register, name ='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name ='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name ='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swappers/base/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.template.defaultfilters import slugify
from django.urls import reverse

class Post(models.Model):
    name = models.CharField(max_length=100)
    # bio = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_image', blank = True)
    # productPic = models.ImageField(upload_to='profile_image', blank = True)
    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    bio = models.TextField(default="Hello, I am newbie here")
    PFeaturedimage = models.ImageField(default='Pdefault.jpg', upload_to='PFeatured_pics')
    PFeaturedimage2 = models.ImageField(default='Pdefault.jpg', upload_to='PFeatured_pics2')
    TFeaturedimage = models.ImageField(default='Tdefault.jpg', upload_to='TFeatured_pics')
    TFeaturedimage2 = models.ImageField(default='Tdefault.jpg', upload_to='TFeatured_pics2')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

class ProductPic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_pics',
                              verbose_name='Image')
    location = models.TextField()
    title = models.TextField()
    story = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    
    
    def save(self, *args, **kwargs):
        super(ProductPic, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 350 or img.width > 900:
            output_size = (350,900)
            img.thumbnail(output_size)
            img.save(self.image.path)
    
    def __str__(self):
        return str(self.item) + ": $" + str(self.price)


    def __str__(self):
        return f'{self.user.username} Product'

    def get_absolute_url(self):
        return reverse('base:post-detail', kwargs={'pk': self.pk})

    
class TravelPic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='travel_pics',
                              verbose_name='Image')
    location = models.TextField()
    title = models.TextField()
    story = models.TextField()
    TravelExpenses = models.DecimalField(max_digits=10, decimal_places=2)
    
    
    def save(self, *args, **kwargs):
        super(TravelPic, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 350 or img.width > 900:
            output_size = (350,900)
            img.thumbnail(output_size)
            img.save(self.image.path)
    
    def __str__(self):
        return str(self.item) + ": $" + str(self.TravelExpenses)

    def __str__(self):
        return f'{self.user.username} Travel'

    def get_absolute_url(self):
        return reverse('base:travel-detail', kwargs={'pk': self.pk})

class FoodPic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='food_pics',
                              verbose_name='Image')
    location = models.TextField()
    title = models.TextField()
    story = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    
    
    def save(self, *args, **kwargs):
        super(FoodPic, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 350 or img.width > 900:
            output_size = (350,900)
            img.thumbnail(output_size)
            img.save(self.image.path)
    
    def __str__(self):
        return str(self.item) + ": $" + str(self.price)


    def __str__(self):
        return f'{self.user.username} Food'

    def get_absolute_url(self):
        return reverse('base:food-detail', kwargs={'pk': self.pk})

    

swappers/base/forms.py
from django import forms
from base.models import ProductPic, TravelPic, FoodPic

class ProductPicForm(forms.ModelForm):
    class Meta:
        model = ProductPic
        fields = ('image', 'location', 'title', 'story', 'price')

class TravelPicForm(forms.ModelForm):
    class Meta:
        model = TravelPic
        fields = ('image', 'location', 'title', 'story', 'TravelExpenses')

class FoodPicForm(forms.ModelForm):
    class Meta:
        model = FoodPic
        fields = ('image', 'location', 'title', 'story', 'price')

    

swappers/base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from .serializers import UserSerializer, GroupSerializer
from django.contrib.auth.decorators import login_required
from .models import Post, Profile, ProductPic, TravelPic, FoodPic
from user.forms import UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from base.forms import ProductPicForm, TravelPicForm, FoodPicForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

@login_required
def home(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                    request.FILES,
                                    instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('base:base-home') 
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': u_form,
        'p_form': p_form,
        'posts': Post.objects.all(),
        'productpics': ProductPic.objects.all()
    }
    return render(request, 'base/home.html', context)

@login_required
def gallery(request):
    context = {
        'posts': Post.objects.all(),
        'productpics': ProductPic.objects.all()
    }
    return render(request, 'base/gallery.html', context)

@login_required
def travel(request):
    context = {
        'posts': Post.objects.all(),
        'travelpics': TravelPic.objects.all()
        # 'productpics': ProductPic.objects.all()
    }
    return render(request, 'base/travel.html', context)

class PostListView(ListView):
    model = ProductPic
    template_name = 'base/gallery.html'
    # context_object_name = 'productpics'

    def get_context_data(self, **kwargs):
        product = ProductPic.objects.filter(user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['productpics'] = product
        return context

class PostDetailView(DetailView):
    model = ProductPic
    template_name = 'base/post_detail.html'

class PostCreateView(LoginRequiredMixin,CreateView):
    model = ProductPic
    template_name = 'base/post_form.html'
    form_class = ProductPicForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url ='/gallery'

class PostUpdateView(LoginRequiredMixin,UpdateView, UserPassesTestMixin):
    model = ProductPic
    template_name = 'base/post_form.html'
    form_class = ProductPicForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        productpic = self.get.object()
        if self.request.user == productpic.user:
            return True
        return False
    
    success_url ='/gallery'

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = ProductPic
    template_name = 'base/post_confirm_delete.html'
    
    success_url ='/gallery'


# for travels
class TravelListView(ListView):
    model = TravelPic
    template_name = 'base/travel.html'
    # context_object_name = 'productpics'

    def get_context_data(self, **kwargs):
        product = TravelPic.objects.filter(user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['travelpics'] = product
        return context

class TravelDetailView(DetailView):
    model = TravelPic
    template_name = 'base/travel_detail.html'

class TravelCreateView(LoginRequiredMixin,CreateView):
    model = TravelPic
    template_name = 'base/travelpost_form.html'
    form_class = TravelPicForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url ='/travel/'

class TravelUpdateView(LoginRequiredMixin,UpdateView, UserPassesTestMixin):
    model = TravelPic
    template_name = 'base/travelpost_form.html'
    form_class = TravelPicForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        travelpic = self.get.object()
        if self.request.user == travelpic.user:
            return True
        return False
    success_url ='/travel/'
class TravelDeleteView(LoginRequiredMixin,DeleteView):
    model = TravelPic
    template_name = 'base/travelpost_confirm_delete.html'
    
    success_url ='/travel/'


# For Food Pictures
class FoodListView(ListView):
    model = FoodPic
    template_name = 'base/food.html'
    # context_object_name = 'productpics'

    def get_context_data(self, **kwargs):
        product = FoodPic.objects.filter(user=self.request.user)

        context = super().get_context_data(**kwargs)
        context['foodpics'] = product
        return context

class FoodDetailView(DetailView):
    model = FoodPic
    template_name = 'base/food_detail.html'

class FoodCreateView(LoginRequiredMixin,CreateView):
    model = FoodPic
    template_name = 'base/foodpost_form.html'
    form_class = FoodPicForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    success_url ='/food/'

class FoodUpdateView(LoginRequiredMixin,UpdateView, UserPassesTestMixin):
    model = FoodPic
    template_name = 'base/foodpost_form.html'
    form_class = FoodPicForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        Foodpic = self.get.object()
        if self.request.user == Foodpic.user:
            return True
        return False
    success_url ='/food/'
class FoodDeleteView(LoginRequiredMixin,DeleteView):
    model = FoodPic
    template_name = 'base/foodpost_confirm_delete.html'
    
    success_url ='/food'


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

swappers/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blogger</title>
    <link href="{% static '/css/main.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/dark-mode.css' %}" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js "></script>
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <script src="dark-mode-switch.min.js"></script>

</head>

<body class="bg-white">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">{{ user.username }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'base:base-home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'base:base-gallery' %}">Product</a>
                    <!-- <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                          </a> -->
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'base:base-travel' %}">Travels</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'base:base-food' %}">Food</a>
                </li>
                <!-- <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li> -->
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>  -->
                {% if user.is_authenticated %}
                <button class="btn  my-2 my-sm-0"><a href="{% url 'logout' %}">Logout</a></button> {% else %}
                <button class="btn my-2 my-sm-0"><a href="{% url 'login' %}">Login</a></button>
                <button class="btn my-2 my-sm-0"><a href="{% url 'register' %}">Register</a></button> {% endif %}
            </form>
            <div class="custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" id="darkSwitch">
                <label class="custom-control-label" style="color: white;" for="darkSwitch">Dark Mode</label>
            </div>
        </div>
    </nav>
    <main role="main">
        <div class="wrapper">
            {% if messages %} {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
            {% endfor %} {% endif %} {% block content %} {% endblock %}
        </div>
    </main>
</body>
<hr>

<script>
    $(function() {
        $("#mdb-lightbox-ui ").load("mdb-addons/mdb-lightbox-ui.html ");
    });
</script>

<script type="text/javascript" src="{% static 'js/dark-mode-switch.js' %}"></script>

</html>

swappers/base/templates/base/food.html
{% extends 'base/base.html' %} {% load static %} {% block content %}

<a href="{% url 'base:food-create' %}" class="btn btn-primary d-block m-4">Share a Post</a><br> {% for post in foodpics %}
<hr>
<div class="container p-3 card card-body bg-dark">
    <div class="row">

        <div class="col-md-4">
            <div class="card card-body bg-white" id="profile-wrapper">
                <img class="img-fluid" id="" src="{{ post.image.url }}" />
                <!-- <hr> -->
                <!-- {% for post in posts %} -->
                <!-- {% endfor %} -->
            </div>
        </div>
        <div class="col-md-8">

            <div class="card card-body bg-white">
                <div class="row">
                    <h5 class="col-sm-8"> <a href="{% url 'base:food-detail' pk=post.pk %}">{{ post.title }}</a></h5>
                    <!-- <button class="col-sm-2 btn btn-danger float-right" data-toggle="modal" data-target="#delModal">Delete</button> -->
                    <button class="col-sm-2 btn btn-outline-danger float-right"><a href="{% url 'base:food-delete' pk=post.pk %}">Delete</a></button>
                    <button class="col-sm-2 btn btn-outline-primary "><a href="{% url 'base:food-update' pk=post.pk %}">Edit</a></button>

                </div>
                <hr>
                <p>Location: {{ post.location }}</p>
                <p class="d-inline-flex font-italic">Price: {{ post.price }}</p>
                <!-- <button id="editbutton" class="btn btn-secondary button5" data-toggle="modal" data-target="#exampleModalLong1">Edit Profile</button> -->
                <p>{{ post.story }}</p>
            </div>

        </div>

    </div>
</div>
<hr> {% endfor %}
<div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Are you Sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
            </div>
            <div class="modal-body text-center">
                <button type="button" class="btn btn-danger">Delete Post</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            </div>

        </div>
    </div>
</div>

{% endblock %}

swappers/base/templates/base/food_detail.html
{% extends 'base/base.html' %} {% load static %} {% block content %}

<a href="{% url 'base:base-food' %}" class="btn btn-info d-block m-4">Go Back to Food Gallery</a>
<hr>
<div class="container p-3 card card-body bg-dark">
    <div class="row">

        <div class="col-md-4">
            <div class="card card-body bg-white" id="profile-wrapper">
                <img class="img-fluid" src="{{ object.image.url }}" />
            </div>
        </div>
        <div class="col-md-8">

            <div class="card card-body bg-white">
                <div class="row">
                    <h5 class="col-sm-10"> {{ object.title }}</h5>
                    <!-- <button class="col-sm-2 btn btn-danger float-right"><a href="base:post-delete">Delete</a></button> -->

                </div>
                <hr>
                <p>Location: {{ object.location }}</p>
                <p class="d-inline-flex font-italic">Price: {{ object.price }}</p>
                <!-- <button id="editbutton" class="btn btn-secondary button5" data-toggle="modal" data-target="#exampleModalLong1">Edit Profile</button> -->
                <p>{{ object.story }}</p>
            </div>

        </div>

    </div>
</div>
<hr>
<!-- <div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Are you Sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
            </div>
            <div class="modal-body text-center">
                <button type="button" class="btn btn-danger">Delete Post</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            </div>

        </div>
    </div>
</div> -->

{% endblock %}

swappers/base/templates/base/gallery.html
{% extends 'base/base.html' %} {% load static %} {% block content %}
<a href="{% url 'base:post-create' %}" class="btn btn-primary d-block m-4">Share a Post</a> {% for post in productpics %}
<hr>
<div class="container p-3 card card-body bg-dark">
    <div class="row">

        <div class="col-md-4">
            <div class="card card-body bg-white" id="profile-wrapper">
                <img class="img-fluid" id="productpic" src="{{ post.image.url }}" />
                <!-- <hr> -->
                <!-- {% for post in posts %} -->
                <!-- {% endfor %} -->
            </div>
        </div>
        <div class="col-md-8">

            <div class="card card-body bg-white">
                <div class="row">
                    <h5 class="col-sm-8"> <a href="{% url 'base:post-detail' pk=post.pk %}">{{ post.title }}</a></h5>
                    <!-- <button class="col-sm-2 btn btn-danger float-right" data-toggle="modal" data-target="#delModal">Delete</button> -->
                    <button class="col-sm-2 btn btn-outline-danger float-right"><a href="{% url 'base:post-delete' pk=post.pk %}">Delete</a></button>
                    <button class="col-sm-2 btn btn-outline-primary "><a href="{% url 'base:post-update' pk=post.pk %}">Edit</a></button>

                </div>
                <hr>
                <p>Location: {{ post.location }}</p>
                <p class="d-inline-flex font-italic">Price: {{ post.price }}</p>
                <!-- <button id="editbutton" class="btn btn-secondary button5" data-toggle="modal" data-target="#exampleModalLong1">Edit Profile</button> -->
                <p>{{ post.story }}</p>
            </div>

        </div>

    </div>
</div>
<hr> {% endfor %}
<div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Are you Sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
            </div>
            <div class="modal-body text-center">
                <button type="button" class="btn btn-danger">Delete Post</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            </div>

        </div>
    </div>
</div>

{% endblock %}

swappers/base/templates/base/travel.html
{% extends 'base/base.html' %} {% load static %} {% block content %}

<a href="{% url 'base:travel-create' %}" class="btn btn-primary d-block m-4">Share a Post</a><br> {% for post in travelpics %}
<hr>
<div class="container p-3 card card-body bg-dark">
    <div class="row">

        <div class="col-md-4">
            <div class="card card-body bg-white" id="profile-wrapper">
                <img class="img-fluid" id="" src="{{ post.image.url }}" />
                <!-- <hr> -->
                <!-- {% for post in posts %} -->
                <!-- {% endfor %} -->
            </div>
        </div>
        <div class="col-md-8">

            <div class="card card-body bg-white">
                <div class="row">
                    <h5 class="col-sm-8"> <a href="{% url 'base:travel-detail' pk=post.pk %}">{{ post.title }}</a></h5>
                    <!-- <button class="col-sm-2 btn btn-danger float-right" data-toggle="modal" data-target="#delModal">Delete</button> -->
                    <button class="col-sm-2 btn btn-outline-danger float-right"><a href="{% url 'base:travel-delete' pk=post.pk %}">Delete</a></button>
                    <button class="col-sm-2 btn btn-outline-primary "><a href="{% url 'base:travel-update' pk=post.pk %}">Edit</a></button>

                </div>
                <hr>
                <p>Location: {{ post.location }}</p>
                <p class="d-inline-flex font-italic">Travel Expenses: {{ post.TravelExpenses }}</p>
                <!-- <button id="editbutton" class="btn btn-secondary button5" data-toggle="modal" data-target="#exampleModalLong1">Edit Profile</button> -->
                <p>{{ post.story }}</p>
            </div>

        </div>

    </div>
</div>
<hr> {% endfor %}
<div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Are you Sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
            </div>
            <div class="modal-body text-center">
                <button type="button" class="btn btn-danger">Delete Post</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            </div>

        </div>
    </div>
</div>

{% endblock %}